name: Deploy to Vercel

on:
  push:
    branches:
      - master # Cambia según tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    env: # Variables de entorno disponibles para todos los pasos del trabajo
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Generate Prisma client and run migrations
        run: |
          npx prisma generate
          npx prisma migrate deploy

      - name: Deploy to Vercel
        env: # Solo necesitas agregar variables adicionales aquí si no están en la sección global
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: npx vercel deploy --prod --yes --token=$VERCEL_TOKEN --debug